# Generated by Django 4.2.7 on 2025-08-03 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='South Africa', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='ads.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='ads.province')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(choices=[('ZAR', 'ZAR'), ('USD', 'USD'), ('MWK', 'MWK')], default='ZAR', max_length=3)),
                ('currency_symbol', models.CharField(choices=[('R', 'R'), ('$', '$'), ('MK', 'MK')], default='R', max_length=5)),
                ('ad_type', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('wanted', 'Wanted')], default='for_sale', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending_approval', max_length=20)),
                ('contact_visibility', models.CharField(choices=[('by_request', 'By Request'), ('registered', 'Registered Users'), ('public', 'Public')], max_length=20)),
                ('contact_method', models.CharField(choices=[('phone', 'Phone Only'), ('email', 'Email Only'), ('both', 'Both')], default='both', max_length=5)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('inquiries', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.province')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AdMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='URL to the media file')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=5)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ads.ad')),
            ],
            options={
                'verbose_name_plural': 'Ad media',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['ad', 'media_type'], name='ads_admedia_ad_id_c03d87_idx'), models.Index(fields=['ad', 'is_thumbnail'], name='ads_admedia_ad_id_ee33f6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'created_at'], name='ads_ad_status_f0db0f_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['subcategory'], name='ads_ad_subcate_98da10_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['city'], name='ads_ad_city_id_8008d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['price'], name='ads_ad_price_b613fd_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['author'], name='ads_ad_author__77046e_idx'),
        ),
    ]
