# Generated by Django 4.2.7 on 2025-08-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-3 code', max_length=3, unique=True)),
                ('currency_code', models.CharField(help_text='ISO 4217 currency code', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['province'], name='ads_ad_provinc_90a179_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['country', 'name'], name='ads_provinc_country_3a8b71_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='ads_country_name_9983e0_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['code'], name='ads_country_code_641af7_idx'),
        ),
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='ads.country'),
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('country', 'name')},
        ),
    ]
