# Generated by Django 4.2.7 on 2025-08-06 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_country_ad_ads_ad_provinc_90a179_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ads.country'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['country'], name='ads_ad_country_479166_idx'),
        ),
    ]
